version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name:  Install dependencies
          command: pip install -r requirements-test.txt
      - run:
          name: pre-commit
          command: pre-commit run --all-files
      - run:
          name: Run tests
          command: pytest --junitxml=test-results/junit.xml --cov --cov-report=xml --xdoctest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - codecov/upload

workflows:
  test:
    jobs:
      - test
